name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    #- name: Test
    #  env:
    #      BCEX_API_KEY: ${{ secrets.BCEX_API_KEY }}
    #      BCEX_API_SECRET: ${{ secrets.BCEX_API_SECRET }}
    #  run: go test -v ./...

    - name: Publish doc to go.dev packages
      run: |
        git pull
        export latest="$(git describe --tags `git rev-list --tags --max-count=1`)"
        curl https://proxy.golang.org/github.com/hmedkouri/go-bcex/@v/$latest.info
